name: Release
on: push
jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        use_efi: ['true', 'false']
    steps:
      - uses: actions/checkout@v2
      - run: make USE_EFI=${{ matrix.use_efi }} all
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            build/output${{ matrix.use_efi == 'true' && '-efi' || '' }}.iso

